# Netlify Configuration for DigiGet
[build]
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

